name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HelloAndroid-APK
          path: bin/*.apk
